SELECT NOM, DATE_NAISSANCE, SALAIRE FROM EMPLOYES
WHERE DATE_NAISSANCE < '01/01/1966';

declare
   v_date   DATE := '01/01/1966';
   v_pct    NUMBER(4,3) := 1.05;
begin
   UPDATE EMPLOYES SET SALAIRE = SALAIRE * v_pct
   WHERE DATE_NAISSANCE < v_date;
end;
/

SELECT NOM, DATE_NAISSANCE, SALAIRE FROM EMPLOYES
WHERE DATE_NAISSANCE < '01/01/1966';

rollback;
