CREATE OR REPLACE TRIGGER AvantMiseAJourEnregCat
BEFORE INSERT ON CATEGORIES
FOR EACH ROW
BEGIN
    :new.code_categorie := scat.NEXTVAL;
END AvantMiseAJourEnregCat;
/

CREATE TABLE EMPLOYES_SAV
AS SELECT NO_EMPLOYE,REND_COMPTE,NOM,PRENOM,
	FONCTION,TITRE,DATE_NAISSANCE,DATE_EMBAUCHE,
	SALAIRE,COMMISSION,PAYS,REGION,
    USER UTILISATEUR,SYSDATE DATE_JOUR
	FROM EMPLOYES WHERE 1=2;
	
CREATE OR REPLACE TRIGGER 
     ApresMiseAJourEnregEmployes
AFTER UPDATE or DELETE ON EMPLOYES
FOR EACH ROW
BEGIN
    insert into employes_sav
	values ( :old.NO_EMPLOYE,:old.REND_COMPTE,:old.NOM,:old.PRENOM,
		:old.FONCTION,:old.TITRE,:old.DATE_NAISSANCE,:old.DATE_EMBAUCHE,
		:old.SALAIRE,:old.COMMISSION,:old.PAYS,:old.REGION,USER ,SYSDATE);

END AvantMiseAJourEnregCat;
/

	
CREATE OR REPLACE TRIGGER ApresMiseAJourEnregEmployes
AFTER UPDATE or DELETE ON EMPLOYES
FOR EACH ROW
declare 
  pragma autonomous_transaction;
BEGIN
    insert into employes_sav
	values ( :old.NO_EMPLOYE,:old.REND_COMPTE,:old.NOM,:old.PRENOM,
		:old.FONCTION,:old.TITRE,:old.DATE_NAISSANCE,:old.DATE_EMBAUCHE,
		:old.SALAIRE,:old.COMMISSION,:old.PAYS,:old.REGION,USER ,SYSDATE);
    commit;	
END AvantMiseAJourEnregCat;
/

